name: 'AI Test Helper'
description: 'AI-powered test code generation for pull requests using Claude or Gemini'
author: 'k1my3ch4n'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  ai_provider:
    description: 'AI provider to use (claude or gemini)'
    required: true
  ai_api_key:
    description: 'API key for the AI provider'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  ai_model:
    description: 'Specific AI model to use (optional)'
    required: false
  output_dir:
    description: 'Directory to save generated test files'
    required: false
    default: './generated-tests'
  test_framework:
    description: 'Test framework to use (jest, mocha, vitest, pytest, junit, auto)'
    required: false
    default: 'auto'
  add_comment:
    description: 'Add test suggestions as PR comment'
    required: false
    default: 'true'

outputs:
  suggestions:
    description: 'JSON array of test suggestions'
  generated_tests:
    description: 'JSON array of generated test file names'
  success:
    description: 'Whether test generation was successful'

runs:
  using: 'node20'
  main: 'dist/index.js'
