import * as core from '@actions/core';
import * as github from '@actions/github';
import { createAIClient, parseProvider } from './api';
import { GitAnalyzer } from './git';
import { TestGenerator } from './generator';

async function run(): Promise<void> {
  try {
    core.info('AI Test Helper started');

    // 1. 입력값 가져오기
    const aiProvider = core.getInput('ai_provider', { required: true });
    const aiApiKey = core.getInput('ai_api_key', { required: true });
    const githubToken = core.getInput('github_token', { required: true });
    const aiModel = core.getInput('ai_model') || undefined;
    const outputDir = core.getInput('output_dir') || './generated-tests';
    const testFramework = core.getInput('test_framework') || 'auto';

    // 2. PR 번호 확인
    const context = github.context;
    const prNumber = context.payload.pull_request?.number;

    if (!prNumber) {
      core.setFailed('This action must be run on a pull request event');
      return;
    }

    core.info(`Processing PR #${prNumber}`);

    // 3. AI 클라이언트 생성
    const provider = parseProvider(aiProvider);
    const aiClient = createAIClient({
      provider,
      apiKey: aiApiKey,
      model: aiModel,
    });

    core.info(`Using AI provider: ${provider}`);

    // 4. Git 분석기 생성 및 PR 분석
    const gitAnalyzer = new GitAnalyzer(githubToken);
    const analysisResult = await gitAnalyzer.analyzePullRequest(prNumber);

    core.info(`Found ${analysisResult.changedFiles.length} changed files`);

    // 5. 코드 파일만 필터링
    const codeFiles = gitAnalyzer.filterCodeFiles(analysisResult.changedFiles);

    if (codeFiles.length === 0) {
      core.info('No code files to analyze');
      core.setOutput('suggestions', JSON.stringify([]));
      core.setOutput('generated_tests', JSON.stringify([]));
      return;
    }

    core.info(`Processing ${codeFiles.length} code files`);

    // 6. 테스트 생성기 생성
    const testGenerator = new TestGenerator(aiClient, {
      outputDir,
      testFramework: testFramework as 'jest' | 'mocha' | 'vitest' | 'pytest' | 'junit' | 'auto',
      language: 'auto',
    });

    // 7. 파일 내용 가져오는 함수
    const getFileContent = async (filePath: string): Promise<string> => {
      return gitAnalyzer.getFileContent(filePath, analysisResult.pullRequest?.headBranch || 'HEAD');
    };

    // 8. 테스트 생성
    const testResult = await testGenerator.generateTests(
      codeFiles,
      analysisResult.diff,
      getFileContent
    );

    // 9. 결과 출력
    core.info(`Generated ${testResult.suggestions.length} test suggestions`);
    core.info(`Generated ${testResult.generatedTests.length} test files`);

    // 10. 생성된 테스트 파일 저장
    if (testResult.generatedTests.length > 0) {
      const savedFiles = await testGenerator.saveGeneratedTests(testResult.generatedTests);
      core.info(`Saved ${savedFiles.length} test files to ${outputDir}`);
    }

    // 11. 출력 설정
    core.setOutput('suggestions', JSON.stringify(testResult.suggestions));
    core.setOutput(
      'generated_tests',
      JSON.stringify(testResult.generatedTests.map((t) => t.fileName))
    );
    core.setOutput('success', testResult.success.toString());

    if (testResult.errors.length > 0) {
      core.warning(`Errors occurred: ${testResult.errors.join(', ')}`);
    }

    // 12. PR에 코멘트 작성 (선택적)
    const addComment = core.getInput('add_comment') === 'true';
    if (addComment && testResult.suggestions.length > 0) {
      await addPRComment(githubToken, prNumber, testResult.suggestions);
    }

    core.info('AI Test Helper completed successfully');
  } catch (error) {
    if (error instanceof Error) {
      core.setFailed(error.message);
    } else {
      core.setFailed('An unexpected error occurred');
    }
  }
}

/**
 * PR에 테스트 제안 코멘트 작성
 */
async function addPRComment(
  token: string,
  prNumber: number,
  suggestions: Array<{ description: string; priority: string; type: string }>
): Promise<void> {
  const octokit = github.getOctokit(token);
  const context = github.context;

  const suggestionList = suggestions
    .map((s) => `- **[${s.priority.toUpperCase()}]** (${s.type}) ${s.description}`)
    .join('\n');

  const body = `## AI Test Helper - Test Suggestions

The following tests are suggested for this PR:

${suggestionList}

---
*Generated by AI Test Helper*`;

  await octokit.rest.issues.createComment({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: prNumber,
    body,
  });

  core.info('Added test suggestions comment to PR');
}

run();
